---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - "10.2.16.1-10.2.16.255"

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-announcement
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool


