---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radicale
  namespace: radicale
  labels:
    app: radicale
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: radicale
  template:
    metadata:
      labels:
        app: radicale
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: radicale-pvc
      containers:
        - name: radicale
          image: tomsquest/docker-radicale
          ports:
            - name: http
              containerPort: 5232
          volumeMounts:
            - name: data
              mountPath: /data
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: radicale
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: radicale
  type: LoadBalancer
