apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server-js-pvc
  namespace: matter
  labels:
    backup: daily
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
  namespace: matter 
  labels:
    app: matter-server
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: matter-server
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      hostNetwork: true 
      dnsPolicy: ClusterFirstWithHostNet # Ensures the pod can still resolve K8s ClusterIP services
      containers:
        - name: matter-js-server
          image: ghcr.io/matter-js/matterjs-server:1.1.7 
          securityContext:
            privileged: false 
            runAsUser: 1000 
          ports:
            - containerPort: 5580
              hostPort: 5580
              name: ws-port
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: matter-data
      volumes:
        - name: matter-data
          persistentVolumeClaim:
            claimName: matter-server-js-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: matter-server-service
  namespace: matter 
spec:
  type: ClusterIP
  selector:
    app: matter-server
  ports:
    - name: ws-port
      protocol: TCP
      port: 5580
      targetPort: 5580
