# https://cloudnative-pg.io/documentation/1.16/backup_recovery/
apiVersion: v1
kind: Secret
metadata:
  name: versity-secret
  namespace: cnpg-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: YWRtaW4=
  AWS_SECRET_ACCESS_KEY: YWRtaW4= 
