apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: "Apps"
    favicon: https://kubernetes.io
  
  services.yaml: |
    - Media:
        - Jellyfin:
            icon: jellyfin
            href: http://nas.home:30013
            description: Media server
        - Jellyfin (alt):
            icon: jellyfin
            href: http://192.168.2.200:30013
            description: Media server
        - Radarr:
            icon: radarr
            href: https://radarr.k8s.tolly-home.com
            description: Movies
        - Sonarr:
            icon: sonarr
            href: https://sonarr.k8s.tolly-home.com
            description: TV series
        - Prowlarr:
            icon: prowlarr
            href: https://prowlarr.k8s.tolly-home.com
            description: Usenet indexer management
        - NzbGet:
            icon: nzbget
            href: https://nzbget.k8s.tolly-home.com
            description: Download client
    - Books:
        - Sonarr:
            icon: bookorbit
            href: https://bookorbit.k8s.tolly-home.com
            description: Library
        - Chaptarr:
            icon: chaptarr
            href: https://chaptarr.k8s.tolly-home.com
            description: Book downloads
    - Home automation:
        - "Home assistant":
            icon: home-assistant
            href: https://ha.k8s.tolly-home.com
            description: Home assistant
        - Frigate:
            icon: frigate
            href: http://frigate.home
            description: Cameras
    - Tools:
        - Immich:
            icon: immich
            href: https://immich.k8s.tolly-home.com
            description: Photos
        - Vaultwarden:
            icon: vaultwarden
            href: https://vault.k8s.tolly-home.com
            description: Passwords
        - Mealie:
            icon: mealie
            href: https://mealie.k8s.tolly-home.com
            description: Recipes 
        - Paperless-ngx:
            icon: paperless
            href: https://docs.k8s.tolly-home.com
            description: Documents
        - LubeLogger:
            icon: lubelogger
            href: https://lubelogger.k8s.tolly-home.com
            description: Car servicing
        - Planka
            icon: planka
            href: https://planka.k8s.tolly-home.com
            description: Kanban board
    - Infrastructure:
        - TrueNAS:
            icon: truenas
            href: http://nas.home
            description: Storage
        - ArgoCD:
            icon: argocd
            href: http://10.2.16.1
            description: GitOps deployments
        - Longhorn:
            icon: longhorn
            href: http://10.2.16.2
            description: Distributed storage

            
            
  bookmarks.yaml: |
    []

