apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: "Apps"
    favicon: https://kubernetes.io
  
  services.yaml: |
    - Media:
        - Jellyfin:
            icon: jellyfin
            href: http://nas.home:30013
            description: Media server
        - Jellyfin (alt):
            icon: jellyfin
            href: http://192.168.2.200:30013
            description: Media server
        - Radarr:
            icon: radarr
            href: https://radarr.k8s.tolly-home.com
            description: Movies
        - Sonarr:
            icon: sonarr
            href: https://sonarr.k8s.tolly-home.com
            description: TV series
    - Books:
        - Sonarr:
            icon: bookorbit
            href: https://bookorbit.k8s.tolly-home.com
            description: Library
        - Chaptarr:
            icon: readarr
            href: https://chaptarr.k8s.tolly-home.com
            description: Book downloads
            

