---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  labels:
    backup: daily
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
  labels:
    app: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-pvc
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.36.0-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data/
          env: 
            - name: DOMAIN
              value: https://vault.k8s.tolly-home.com
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-pg-cluster-app
                  key: uri
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: vaultwarden
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: dns-issuer
  name: vaultwarden-gateway
spec:
  gatewayClassName: eg
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: vault.k8s.tolly-home.com
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: vaultwarden-https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
spec:
  parentRefs:
    - name: vaultwarden-gateway
  hostnames:
    - vault.k8s.tolly-home.com
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: vaultwarden
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
      timeouts:
        request: "30s"
