# Firefly III

apiVersion: v1
kind: Service
metadata:
  name: firefly
  labels:
    app: firefly
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: firefly

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-pvc
  labels:
    app: firefly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly
  labels:
    app: firefly
spec:
  selector:
    matchLabels:
      app: firefly
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: firefly
    spec:
      containers:
      - image: fireflyiii/core:version-6.2.12
        name: firefly-iii
        env:
        - name: APP_ENV
          value: "local"
        - name: APP_KEY
          value: "test-key" # TODO change this
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: firefly-pg-cluster-app
              key: host
        - name: DB_CONNECTION
          value: pgsql
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: firefly-pg-cluster-app
              key: dbname
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: firefly-pg-cluster-app
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: firefly-pg-cluster-app
              key: password
        - name: TRUSTED_PROXIES
          value: "**"
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - mountPath: "/var/www/html/storage/upload"
          name: firefly-iii-upload
        imagePullPolicy: Always
      volumes:
        - name: firefly-iii-upload
          persistentVolumeClaim:
            claimName: firefly-pvc
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: firefly-pg-cluster
spec:
  instances: 1
  storage:
    size: 10Gi
