---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: multimedia
  labels:
    app: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bazarr-pvc
        - name: movies
          nfs:
            server: nas.home
            path: /mnt/nas/media/Movies
            readonly: false
        - name: tv
          nfs:
            server: nas.home
            path: /mnt/nas/media/Series
            readonly: false
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:1.5.6
          ports:
            - name: http
              containerPort: 6767
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Australia/Sydney
          volumeMounts:
            - name: data
              mountPath: /config
            - name: movies
              mountPath: /movies
            - name: tv
              mountPath: /tv
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: bazarr
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: bazarr
  type: LoadBalancer
---
