---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: multimedia
  labels:
    app: jellyfin
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-pvc
        - name: media
          nfs:
            server: nas.home
            path: /mnt/nas/media
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:2025090105
          ports:
            - name: http
              containerPort: 8096
          env:
            - name: JELLYFIN_PublishedServerUrl
              value: http://jellyfin.home
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: jellyfin
  type: LoadBalancer
---
