---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-tmp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: multimedia
  labels:
    app: nzbget
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: nzbget-config-pvc
        - name: tmp
          persistentVolumeClaim:
            claimName: nzbget-tmp-pvc
      containers:
        - name: nzbget
          image: lscr.io/linuxserver/nzbget:25.2.20250822
          ports:
            - name: http
              containerPort: 6789
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Australia/Sydney
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tmp
              mountPath: /intermediate
            # TODO mounts for dl client out
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: nzbget
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: nzbget
  type: LoadBalancer
---
