---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: multimedia
  labels:
    app: prowlarr
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: prowlarr-pvc
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:2.0.5
          ports:
            - name: http
              containerPort: 9696
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Australia/Sydney
          volumeMounts:
            - name: data
              mountPath: /config
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: prowlarr
  type: LoadBalancer
---
