---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: multimedia
  labels:
    app: radarr
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: radarr-pvc
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:5.26.2
          ports:
            - name: http
              containerPort: 7878
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Australia/Sydney
          volumeMounts:
            - name: data
              mountPath: /config
            # TODO mounts for dl client and media lib
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: radarr
  type: LoadBalancer
---
