---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
      # TODO can this just be configMaps? All secrets should be in prowlarr
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: multimedia
  labels:
    app: sonarr
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sonarr-pvc
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:4.0.15
          ports:
            - name: http
              containerPort: 8989
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Australia/Sydney
          volumeMounts:
            - name: data
              mountPath: /config
            # TODO mounts for dl client and media lib
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: sonarr
  type: LoadBalancer
---
