---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: multimedia
  labels:
    app: sonarr
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sonarr-pvc
        - name: media
          nfs:
            server: nas.home
            path: /mnt/nas/media
        - name: tmp
          persistentVolumeClaim:
            claimName: media-tmp-pvc
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:4.0.15
          ports:
            - name: sonarr-http
              containerPort: 8989
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Australia/Sydney
          volumeMounts:
            - name: data
              mountPath: /config
            - name: media
              value: /media
            - name: tmp
              value: /downloads
              subPath: /complete
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: sonarr-http
      name: sonarr-http
  selector:
    app: sonarr
  type: LoadBalancer
---
