---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unmanic-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unmanic
  namespace: multimedia
  labels:
    app: unmanic
    component: main
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: unmanic
  template:
    metadata:
      labels:
        app: unmanic
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: unmanic-data-pvc
        - name: media
          nfs:
            server: nas.home
            path: /mnt/nas/media
            readonly: false
        - name: tmp
          emptyDir: {}
      containers:
        - name: unmanic
          image: josh5/unmanic:0.3.0
          ports:
            - name: http
              containerPort: 8888
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: data
              mountPath: /config
              subPath: main/
            - name: media
              mountPath: /library
            - name: tmp
              mountPath: /tmp/unmanic
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unmanic-worker-1
  namespace: multimedia
  labels:
    app: unmanic
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: unmanic
  template:
    metadata:
      labels:
        app: unmanic
        component: worker-1
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: unmanic-pvc
        - name: media
          nfs:
            server: nas.home
            path: /mnt/nas/media
            readonly: false
        - name: tmp
          emptyDir: {}
      containers:
        - name: unmanic
          image: josh5/unmanic:0.3.0
          ports:
            - name: worker1-http
              containerPort: 8888
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: data
              mountPath: /config
              subPath: worker1/
            - name: media
              mountPath: /library
            - name: tmp
              mountPath: /tmp/unmanic
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: unmanic
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: unmanic
  type: LoadBalancer
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: unmanic-worker-1
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: worker1-http
      name: worker1-http
  selector:
    app: unmanic
    component: worker-1
  type: LoadBalancer
---
