apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual-budget
  namespace: actual-budget
  labels:
    app: actual-budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actual-budget
  template:
    metadata:
      labels:
        app: actual-budget
    spec:
      containers:
        - name: actual-budget
          image: actualbudget/actual-server
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5006
          volumeMounts:
          - name: data-volume
            mountPath: /data
          resources:
            requests:
              memory: 256Mi
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 5006
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5006
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: actual-budget-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: actual-budget
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5006
  selector:
    app: actual-budget


