---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baikal-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baikal
  namespace: baikal
  labels:
    app: baikal
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: baikal
  template:
    metadata:
      labels:
        app: baikal
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: baikal-pvc
      # TODO pg db
      containers:
        - name: baikal
          image: ckulka/baikal:nginx:0.10.1
          ports:
            - name: http
              containerPort: 80
          env:
            - name: APPLY_HOME_ASSISTANT_FIX
              value: 'true'
          volumeMounts:
            - name: data
              mountPath: /var/www/baikal/config
              subPath: config
            - name: data
              mountPath: /var/www/baikal/Specific
              subpath: specific
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: baikal
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: baikal
  type: LoadBalancer
