---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koreader-sync-pvc
  labels:
    backup: daily
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: koreader-sync
  namespace: grimmory
  labels:
    app: koreader-sync
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: koreader-sync
  template:
    metadata:
      labels:
        app: koreader-sync
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: koreader-sync-pvc
      containers:
        - name: koreader-sync
          image: ghcr.io/nperez0111/koreader-sync:0.2.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /app/data
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: koreader-sync
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: koreader-sync
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: dns-issuer
  name: koreader-sync-gateway
spec:
  gatewayClassName: eg
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: koreader-sync.k8s.tolly-home.com
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: koreader-sync-https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
spec:
  parentRefs:
    - name: koreader-sync-gateway
  hostnames:
    - koreader-sync.k8s.tolly-home.com
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: koreader-sync
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
