---
# Create a postgres 15 db with pgvector extension
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-pg-cluster
spec:
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-backups/immich/
      endpointURL: http://s3-gw.versitygw.svc.cluster.local
      s3Credentials:
        accessKeyId:
          name: versity-secret
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: versity-secret
          key: AWS_SECRET_ACCESS_KEY
  instances: 1
  imageName: ghcr.io/mtolhurst/postgresql:15.3-pgvector@sha256:e9c502da08471b5cf1e48290c8624fdc8cee50a9aa370f83f5d357a2470ad00f
  storage:
    size: 2Gi
  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vector
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-example
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: immich-pg-cluster
---
apiVersion: v1
kind: Secret
metadata:
  name: versity-secret
  namespace: cnpg-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: YWRtaW4=
  AWS_SECRET_ACCESS_KEY: YWRtaW4= 

