apiVersion: v1
kind: Service
metadata:
  name: maybe
  labels:
    app: maybe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: maybe

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maybe-pvc
  labels:
    app: maybe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: maybe
  labels:
    app: maybe
spec:
  selector:
    matchLabels:
      app: maybe
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: maybe
    spec:
      containers:
      - image: ghcr.io/maybe-finance/maybe:latest
        name: web
        env: &env
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: maybe-pg-cluster-app
              key: host
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: maybe-pg-cluster-app
              key: dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: maybe-pg-cluster-app
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: maybe-pg-cluster-app
              key: password
        - name: DB_PORT
          value: 5432
        - name: SECRET_KEY_BASE
          value: a7523c3d0ae56415046ad8abae168d71074a79534a7062258f8d1d51ac2f76d3c3bc86d86b6b0b307df30d9a6a90a2066a3fa9e67c5e6f374dbd7dd4e0778e13
        - name: SELF_HOSTED
          value: true
        - name: RAILS_FORCE_SSL
          value: true
        - name: RAILS_ASSUME_SSL
          value: true
        - name: REDIS_URL
          value: redis://127.0.0.1:6379/1
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
        - mountPath: "/rails/storage"
          name: maybe-rails-storage
        imagePullPolicy: Always
      - name: worker
        image: ghcr.io/maybe-finance/maybe:latest
        command: bundle exec sidekiq
        env: *env
      - name: redis
        image: redis:latest
      volumes:
        - name: maybe-volume
          persistentVolumeClaim:
            claimName: maybe-pvc
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: maybe-pg-cluster
spec:
  instances: 1
  storage:
    size: 10Gi
