---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual
  labels:
    app: actual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actual
  template:
    metadata:
      labels:
        app: actual
    spec:
      containers:
      - image: docker.io/actualbudget/actual-server:sha-4820331-alpine
        name: actual
        ports:
        - containerPort: 5006
          name: http
        volumeMounts:
        - name: actual-data
          mountPath: /data
      volumes:
      - name: actual-data
        persistentVolumeClaim:
          claimName: actual-pvc
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: actual
  labels:
    app: actual
spec:
  ports:
    - port: 80
      name: http
      protocol: tcp
  selector:
    app: actual
  type: LoadBalancer
