---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual
  labels:
    app: actual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actual
  template:
    metadata:
      labels:
        app: actual
    spec:
      containers:
      - image: docker.io/actualbudget/actual-server:sha-4820331-alpine
        name: actual
        env:
          - name: ACTUAL_PORT
            value: "5006"
        ports:
        - containerPort: 5006
          name: http
        volumeMounts:
        - name: actual-data
          mountPath: /data
      volumes:
      - name: actual-data
        persistentVolumeClaim:
          claimName: actual-pvc
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: actual
  labels:
    app: actual
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: http
  selector:
    app: actual
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: dns-issuer
  name: actual-gateway
spec:
  gatewayClassName: eg
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: actual.k8s.tolly-home.com
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: actual-https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
spec:
  parentRefs:
    - name: actual-gateway
  hostnames:
    - actual.k8s.tolly-home.com
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: actual
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
