---
# Create a postgres 15 db
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mealie-pg-cluster
spec:
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: versity-store
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15
  enableSuperuserAccess: true
  storage:
    size: 2Gi
  # # Uncomment this, and comment out the spec.plugins block to restore from backup
  # bootstrap:
  #   recovery:
  #     source: mealie-pg-cluster
  # externalClusters:
  # - name: mealie-pg-cluster
  #   plugin:
  #     name: barman-cloud.cloudnative-pg.io
  #     parameters:
  #       barmanObjectName: versity-store
  #       serverName: mealie-pg-cluster
---
apiVersion: v1
kind: Secret
metadata:
  name: versity-secret
  namespace: mealie
type: Opaque
data:
  AWS_ACCESS_KEY_ID: YWRtaW4=
  AWS_SECRET_ACCESS_KEY: YWRtaW4= 
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: versity-store
spec:
  configuration:
    destinationPath: s3://cnpg-backups/mealie/
    endpointURL: http://s3-gw.versitygw.svc.cluster.local
    s3Credentials:
      accessKeyId:
        name: versity-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: versity-secret
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-backup
spec:
  schedule: "0 0 0 * * *"  # At midnight every day
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  backupOwnerReference: self
  cluster:
    name: mealie-pg-cluster
