apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io 
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: 
      prune: true 
      selfHeal: true
      allowEmpty: false 
  destination:
    namespace: velero
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: 'https://github.com/kubernetes-csi/external-snapshotter.git'
      path: client/config/crd
      targetRevision: v8.5.0 

    - repoURL: 'https://github.com/kubernetes-csi/external-snapshotter.git'
      path: deploy/kubernetes/snapshot-controller
      targetRevision: v8.5.0 

    - chart: velero
      repoURL: https://vmware-tanzu.github.io/helm-charts
      targetRevision: 12.0.1
      helm:
        valuesObject:
          schedules:
            daily-tagged-pvc-backup:
              schedule: "0 1 * * *" # Daily at 1:00 AM
              template:
                includedResources:
                  - persistentvolumeclaims
                  - persistentvolumes
                labelSelector:
                  matchLabels:
                    backup: "daily"
                snapshotVolumes: true
                ttl: 720h0m0s # Retain for 30 days
          credentials:
            useSecret: true
            secretContents:
              cloud: |
                [default]
                aws_access_key_id = admin
                aws_secret_access_key = admin
          initContainers:
            - name: velero-plugin-for-aws
              image: velero/velero-plugin-for-aws:v1.9.0
              volumeMounts:
                - mountPath: /target
                  name: plugins
          configuration:
            features: EnableCSI 
            volumeSnapshotLocation:
              - name: default
                provider: aws  
                config:
                  region: us-east-1
            backupStorageLocation:
              - name: default
                provider: aws
                bucket: velero
                config:
                  region: us-east-1
                  s3ForcePathStyle: true
                  s3Url: http://s3-gw.versitygw.svc.cluster.local
            
