apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actual-budget
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io 
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: 
      prune: true 
      selfHeal: true
      allowEmpty: false 
  destination:
    namespace: actual-budget
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: {{ .Values.spec.source.repoURL }}
      path: apps/actual-budget
