apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io 
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: 
      prune: true 
      selfHeal: true
      allowEmpty: false 
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: oci://quay.io/jetstack/charts/cert-manager
      targetRevision: 1.19.2
      helm:
        valuesObject:
          crds:
            enabled: true
