apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io 
spec:
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        kubernetes.io/metadata.name: frigate
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
    automated: 
      prune: true 
      selfHeal: true
      allowEmpty: false 
  destination:
    namespace: frigate
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: {{ .Values.spec.source.repoURL }}
      path: apps/frigate
