apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io 
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        kubernetes.io/metadata.name: metallb-system
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/warn: privileged
  destination:
    namespace: metallb
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - chart: metallb
      repoURL: https://metallb.github.io/metallb
      targetRevision: 0.14.9
      valuesObject:
        speaker:
          ignoreExcludeLB: true
    - repoURL: git@github.com:mtolhurst/home-k8s.git
      path: infra/metallb
