apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io 
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: 
      prune: true 
      selfHeal: true
      allowEmpty: false 
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 72.6.3
      helm:
        valuesObject:
          global:
            rbac:
              pspEnabled: false
          kube-state-metrics:
            podSecurityPolicy:
              enabled: false
          prometheus-node-exporter:
            rbac:
              pspEnabled: false
          grafana:
            service:
              type: LoadBalancer
            rbac:
              pspEnabled: false
          alertmanager:
            service:
              type: LoadBalancer
