---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config-pvc
spec:
  storageClassName: longhorn-no-replica
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-data-pvc
spec:
  storageClassName: longhorn-no-replica
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: frigate
  labels:
    app: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      volumes:
        - name: configmap
          configMap:
            name: frigate-config
        - name: config
          persistentVolumeClaim:
            claimName: frigate-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: frigate-data-pvc
        - name: media
          nfs:
            server: nas.home
            path: /mnt/nas/cameras
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
      containers:
        - name: frigate
          image: ghcr.io/blakeblackshear/frigate:0.16.3
          securityContext:
            capabilities:
              add: ["PERFMON"]
          resources:
            requests:
              memory: 512Mi
              gpu.intel.com/i915: 1 # ensuring this is scheduled on a node with GPU
            limits:
              gpu.intel.com/i915: 1 
            ports:
            - name: http
              containerPort: 5000
              protocol: TCP
            - name: http-auth
              containerPort: 8971
              protocol: TCP
            - name: rtmp
              containerPort: 1935
              protocol: TCP
            - name: rtsp
              containerPort: 8554
              protocol: TCP
            - name: webrtc-udp
              containerPort: 8555
              protocol: UDP
            - name: webrtc-tcp
              containerPort: 8555
              protocol: TCP
            - name: go2rtc-admin
              containerPort: 1984
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /config/config.yml
            subPath: config.yaml
            name: configmap
          - mountPath: /media
            name: media
          - name: dshm
            mountPath: /dev/shm
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: frigate
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
    - port: 8971
      protocol: TCP
      targetPort: http-auth
      name: http-auth
    - port: 1935
      protocol: TCP
      targetPort: rtmp
      name: rtmp
    - port: 8554
      protocol: TCP
      targetPort: rtsp
      name: rtsp
    - name: webrtc-tcp
      port: 8555
      protocol: TCP
      targetPort: webrtc-tcp
    - name: webrtc-udp
      port: 8555
      protocol: UDP
      targetPort: webrtc-udp
    - name: go2rtc-admin
      port: 1984
      protocol: TCP
      targetPort: webrtc-tcp
  selector:
    app: frigate
  type: LoadBalancer
