---
# PVC for config
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-pvc
spec:
  storageClassName: longhorn-no-replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app: home-assistant
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: ha-pvc
        - name: backup
          nfs:
            server: nas.home
            path: /mnt/nas/backups/home-assistant
      initContainers:
        - name: ha-init
          image: homeassistant/home-assistant:2026.4.2
          command: ["sh", "-c", "wget -O - https://get.hacs.xyz | bash -"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /config
            - name: backup
              mountPath: /config/backups
      containers:
        - name: ha
          image: homeassistant/home-assistant:2026.4.2
          resources:
            requests:
              memory: 256Mi
          ports:
            - name: http
              containerPort: 8123
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /config
            - name: backup
              mountPath: /config/backups
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: home-assistant
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: dns-issuer
  name: ha-gateway
spec:
  gatewayClassName: eg
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: ha.k8s.tolly-home.com
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: ha-https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
spec:
  parentRefs:
    - name: ha-gateway
  hostnames:
    - ha.k8s.tolly-home.com
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: home-assistant
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
