apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-cpu-cache
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-stt-cpu
  namespace: home-assistant
  labels:
    app: whisper-stt-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper-stt-cpu
  template:
    metadata:
      labels:
        app: whisper-stt-cpu
    spec:
      containers:
        - name: whisper
          image: rhasspy/wyoming-whisper:3.8.1
          imagePullPolicy: IfNotPresent
          args:
            - "--model"
            - "base.en" 
            - "--data-dir"
            - "/data"
            - "--download-dir"
            - "/data"
          ports:
            - containerPort: 10300
              name: wyoming
          resources:
            requests:
              cpu: "1000m"
              memory: "256Mi"
            limits:
              cpu: "4000m"
              memory: "1Gi"
          volumeMounts:
            - mountPath: /data
              name: whisper-data
      volumes:
        - name: whisper-data
          persistentVolumeClaim:
            claimName: whisper-cpu-cache
---
apiVersion: v1
kind: Service
metadata:
  name: whisper-stt-cpu
  namespace: home-assistant
spec:
  type: ClusterIP
  ports:
    - port: 10300
      targetPort: 10300
      name: wyoming
  selector:
    app: whisper-stt-cpu

