---
# TODO prometheus monitoring
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-pg-cluster
spec:
  instances: 1
  storage:
    size: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: versity-secret
  namespace: paperless-ngx
type: Opaque
data:
  AWS_ACCESS_KEY_ID: YWRtaW4=
  AWS_SECRET_ACCESS_KEY: YWRtaW4= 

